# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Environment
        run: |
          echo "APP_VERSION=${{github.run_id}}" >> "$GITHUB_ENV"
          echo "BUILD_AT=$(date +%s)" >> "$GITHUB_ENV"
      - name: Set APP_VERSION
        env:
          APP_VERSION: ${{ env.APP_VERSION }}
          BUILD_AT: ${{ env.BUILD_AT }}
        run: |
          echo `jq '.AppVersion="${{ env.APP_VERSION }}"|.BuildAt=${{ env.BUILD_AT }}' version.json` > version.json
          head version.json
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .   # mandatory, otherwise it will fetch from repo instead of using the current source
          push: true
          tags: |
            liubbqq/boqian-resume:${{ github.run_id }}
            liubbqq/boqian-resume:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E0C76ABC6CFA4C55A87B9EF4F781D94E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5A96FE7B8CAF488880F2F81858B47988 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DB69C5582D954213A8735A0C99F95B0A }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'boqian-resume'
          slot-name: 'Production'
          images: 'liubbqq/boqian-resume:${{ github.run_id }}'
          
      - name: Azure logout
        run: az logout